name: playcardsys-terminal
base: core18
version: 0.1.8
summary: Tauri app.
description: Awesome Tauri app.
grade: stable
confinement: strict
architectures:
  - build-on: armhf
  - build-on: arm64
apps:
  playcardsys-terminal:
    command: playcardsys-terminal
    extensions:
      - gnome-3-34
parts:
  dump-binary:
    plugin: dump
    source: release
    source-type: local
    stage:
      - lib
      - playcardsys-terminal
    prime:
      - lib
      - playcardsys-terminal
    stage-packages:
      - libc6
