name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:

    permissions:
      contents: write

    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-22.04]

    runs-on: ${{ matrix.platform }}

    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install OS (Ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: raspi_3_bullseye:20230102
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: false
          commands: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev patchelf
      
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: npm install
      
      - name: Build the app
        uses: tauri-apps/tauri-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false