name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: ARM runner
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: raspios_lite:latest
          cpu: cortex-a7
          cpu_info: cpuinfo/raspberrypi_3b
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: false
          commands: |
            # Rust complains (rightly) that $HOME doesn't match eid home
            export HOME=/root
            # Workaround to CI worker being stuck on Updating crates.io index
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            apt-get update -y --allow-releaseinfo-change
            apt-get upgrade -y
            apt-get autoremove -y
            apt-get install curl
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            . "$HOME/.cargo/env"
            apt-get install -y libwebkit2gtk-4.0-dev build-essential wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: npm install
      
      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false

      - name: Snapcore Action Build
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          path: './src-tauri/target'

      - name: Save Snap Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

      - name: Snapcraft Action Publish
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge
