name: 'publish'
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu-armv8
            target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.target }}

    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Update and Install Dependencies (Linux)
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev patchelf
      
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      
      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}
      
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: npm install
      
      - name: Build the app
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --target ${{ matrix.target }}
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false